# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1fb9ea543d53335feee8fb0fdad87556f0a708f44e67eebaf9532ef5d5205193dad58171a04836447c403b6a5ea3680911414b5e6a3e34cb259c57eaf790e72

test:
  secret_key_base: 714f79efa246371b3d3cafede863b92410f2c7499c8e1d229b642e5019cb40da85ab6ef018d76272ddbe7f41ef4a1afbdb53f4d14e3e0d38bcd0228be5982aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
